title: Love Thy Law
# email: your-email@example.com
description: >-
  A blog about family law.
domain: lovethylaw.github.io
baseurl: ""
url: https://lovethylaw.github.io

theme: minima
plugins:
  - jekyll-feed
